### ISSUE TITLE
[suggestion] use extra_fit to align pdbs in pymol

### ISSUE THREAD

**Issue by ChloeQuignot** [tubiana/colabfold_singularity#2]
Hi Thibault!

Instead of using `cmd.run('http://pldserver1.biochem.queensu.ca/~rlc/work/pymol/align_all.py')` in `generate_pml.py`, you could try using the `extra_fit` command instead.
cf the wiki https://pymolwiki.org/index.php/Extra_fit, you can also use tmalign if downloaded.

To align on all atoms with b-factor >70 only, you can specify:
`extra_fit b>70`

Thanks for sharing all your scripts, very helpful!
Chloé

**Comment by tubiana** [comment]
Thank you Chloé!

SImpler is better... I completly missed this commands, even after years of pymol usage XD 
It's great that it works with TMalign, I only use that now ;-) 

Best
THibault.
